### ISSUE TITLE
More info if TypeResolver throws a ReflectionTypeLoadException

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sn-tools#2]
When _TypeResolver_ throws a _ReflectionTypeLoadException_ because of one of the libraries, we get only this much information:
> ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

It would be helpful if we converted this well-known exception internally into a more descriptive exception, so that the caller knows what is wrong. Ideally the message of the new wrapper exception would contain the list of specific dlls extracted from the _LoaderExceptions_ property.

**Comment by tusmester** [comment]
**Update**: TypeResolver actually logs the error using _SnLog_, but in my case this happened before anything could be initialized in the application, so this was visible only in the default initial log, which is the _trace log_. So I had to monitor the issue using _DebugView_. 
The problem is that the default _TraceEventLogger_ class simply dumps the message to the trace, which in this case contained a **new line character**. Unfortunately that causes the majority of the error message (e.g. properties that may contain the actual library that would use the dll that could not be loaded) disappear.

I think we should remove new lines from messages before sending them to the Trace in the _TraceEventLogger_ class.

**Comment by kavics** [comment]
**Fixed** in the **FixTypeLoadEx** branch. Pull request: #3
 
TraceEventLogger converts the new line and line feed characters to pipe ('|') without duplicates. So the full message will be one line. Check the new unit test: _SnLog_WriteTypeLoadException_.

The problematic types are inserted to the trace record. This absolutely performs the head of this issue.
